### ISSUE TITLE
[Vssue]基于VuePress搭建博客系统及优化过程（持续更新...） | Duktig

### ISSUE THREAD

**Issue by duktig666** [duktig666/vssues#3]
https://www.duktig.cn/blogs/guan-yu-ben-zhan/ji-yu-vuepressda-jian-bo-ke-xi-tong-ji-you-hua-guo-cheng-chi-xu-geng-xin...-.html

**Comment by duktig666** [comment]
vuepress 搭建的博客还不错

**Comment by kymotz** [comment]
老哥这个网站快多了！猜猜我是谁

**Comment by duktig666** [comment]
@elltor

> 老哥这个网站快多了！猜猜我是谁

qichun，之前那个网站可能是腾讯云服务器的问题，很慢。
这次换了个搭建平台，改用 vuepress 搭建了。

**Comment by kymotz** [comment]
@duktig666

> @elltor
> 
> > 老哥这个网站快多了！猜猜我是谁
> 
> qichun，之前那个网站可能是腾讯云服务器的问题，很慢。
> 这次换了个搭建平台，改用 vuepress 搭建了。

不错，主题看着很轻爽简洁
