### ISSUE TITLE
[Vssue]安利一些电子图书下载网站 | Duktig的个人博客

### ISSUE THREAD

**Issue by duktig666** [duktig666/vssues#35]
https://www.duktig.cn/2022/03/26/%E5%AE%89%E5%88%A9%E4%B8%80%E4%BA%9B%E7%94%B5%E5%AD%90%E5%9B%BE%E4%B9%A6%E4%B8%8B%E8%BD%BD%E7%BD%91%E7%AB%99/

**Comment by kymotz** [comment]
👍👍
